version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  transaction_data_sync_api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    ports:
      - "8000:8000"

volumes:
  postgres_data: